export const EMOJI_CATEGORIES = [
  { id: 'smileys', label: 'Smileys' },
  { id: 'people', label: 'People' },
  { id: 'nature', label: 'Nature' },
  { id: 'food', label: 'Food' },
  { id: 'activities', label: 'Activities' },
  { id: 'travel', label: 'Travel' },
  { id: 'objects', label: 'Objects' },
  { id: 'symbols', label: 'Symbols' },
] as const;

export type EmojiCategoryId = (typeof EMOJI_CATEGORIES)[number]['id'];

export interface Emoji {
  readonly char: string;
  readonly name: string;
  readonly keywords: readonly string[];
  readonly category: EmojiCategoryId;
}

// Curated set focused on kanban/task labeling. Keywords are lowercase and
// intentionally short so the search input matches partial words.
export const EMOJIS: readonly Emoji[] = [
  // Smileys
  { char: '😀', name: 'grinning', keywords: ['happy', 'smile'], category: 'smileys' },
  { char: '😂', name: 'joy', keywords: ['laugh', 'lol', 'cry'], category: 'smileys' },
  { char: '😊', name: 'blush', keywords: ['happy', 'smile'], category: 'smileys' },
  { char: '😉', name: 'wink', keywords: ['flirt'], category: 'smileys' },
  { char: '😍', name: 'heart eyes', keywords: ['love', 'crush'], category: 'smileys' },
  { char: '🤔', name: 'thinking', keywords: ['hmm', 'consider', 'question'], category: 'smileys' },
  { char: '😎', name: 'cool', keywords: ['sunglasses', 'chill'], category: 'smileys' },
  { char: '🤩', name: 'star struck', keywords: ['excited', 'wow'], category: 'smileys' },
  { char: '🥳', name: 'party', keywords: ['celebrate', 'birthday'], category: 'smileys' },
  { char: '😇', name: 'angel', keywords: ['innocent', 'halo'], category: 'smileys' },
  { char: '🙃', name: 'upside down', keywords: ['silly', 'sarcasm'], category: 'smileys' },
  { char: '😴', name: 'sleeping', keywords: ['sleep', 'zzz', 'tired'], category: 'smileys' },
  { char: '🤯', name: 'mind blown', keywords: ['shocked', 'wow'], category: 'smileys' },
  { char: '😱', name: 'scream', keywords: ['scared', 'shocked'], category: 'smileys' },
  { char: '😤', name: 'triumph', keywords: ['determined', 'angry'], category: 'smileys' },
  { char: '😡', name: 'angry', keywords: ['mad', 'rage'], category: 'smileys' },
  { char: '😭', name: 'crying', keywords: ['sad', 'sob', 'tears'], category: 'smileys' },
  { char: '😢', name: 'tear', keywords: ['sad', 'cry'], category: 'smileys' },
  { char: '😔', name: 'pensive', keywords: ['sad', 'thoughtful'], category: 'smileys' },
  { char: '😬', name: 'grimace', keywords: ['awkward', 'yikes'], category: 'smileys' },
  { char: '🤢', name: 'nauseated', keywords: ['sick', 'gross'], category: 'smileys' },
  { char: '🤖', name: 'robot', keywords: ['bot', 'ai', 'android'], category: 'smileys' },
  { char: '👻', name: 'ghost', keywords: ['spooky', 'halloween'], category: 'smileys' },
  { char: '💀', name: 'skull', keywords: ['dead', 'danger'], category: 'smileys' },
  { char: '👽', name: 'alien', keywords: ['ufo', 'space'], category: 'smileys' },
  { char: '🤡', name: 'clown', keywords: ['joke'], category: 'smileys' },
  { char: '💩', name: 'poop', keywords: ['crap', 'bad'], category: 'smileys' },

  // People / Gestures
  {
    char: '👍',
    name: 'thumbs up',
    keywords: ['like', 'approve', 'yes', 'good'],
    category: 'people',
  },
  { char: '👎', name: 'thumbs down', keywords: ['dislike', 'no', 'bad'], category: 'people' },
  { char: '👏', name: 'clap', keywords: ['applause', 'praise'], category: 'people' },
  { char: '🙌', name: 'raised hands', keywords: ['celebrate', 'praise'], category: 'people' },
  { char: '🙏', name: 'pray', keywords: ['thanks', 'please'], category: 'people' },
  { char: '👋', name: 'wave', keywords: ['hi', 'hello', 'bye'], category: 'people' },
  { char: '✌️', name: 'peace', keywords: ['victory', 'two'], category: 'people' },
  { char: '🤞', name: 'crossed fingers', keywords: ['hope', 'luck'], category: 'people' },
  { char: '💪', name: 'muscle', keywords: ['strong', 'flex', 'power'], category: 'people' },
  { char: '🧠', name: 'brain', keywords: ['smart', 'think', 'mind'], category: 'people' },
  { char: '👀', name: 'eyes', keywords: ['look', 'watch', 'see'], category: 'people' },
  { char: '🫡', name: 'salute', keywords: ['respect', 'yes sir'], category: 'people' },
  { char: '🤝', name: 'handshake', keywords: ['deal', 'agreement'], category: 'people' },

  // Nature
  { char: '🐛', name: 'bug', keywords: ['insect', 'defect', 'issue'], category: 'nature' },
  { char: '🐞', name: 'ladybug', keywords: ['bug', 'insect'], category: 'nature' },
  { char: '🐝', name: 'bee', keywords: ['honey', 'buzz'], category: 'nature' },
  { char: '🕷️', name: 'spider', keywords: ['web', 'creepy'], category: 'nature' },
  { char: '🦋', name: 'butterfly', keywords: ['transform'], category: 'nature' },
  { char: '🐶', name: 'dog', keywords: ['puppy', 'pet'], category: 'nature' },
  { char: '🐱', name: 'cat', keywords: ['kitten', 'pet'], category: 'nature' },
  { char: '🦊', name: 'fox', keywords: ['clever'], category: 'nature' },
  { char: '🐻', name: 'bear', keywords: ['grizzly'], category: 'nature' },
  { char: '🦁', name: 'lion', keywords: ['king'], category: 'nature' },
  { char: '🐯', name: 'tiger', keywords: [], category: 'nature' },
  { char: '🐼', name: 'panda', keywords: [], category: 'nature' },
  { char: '🦄', name: 'unicorn', keywords: ['magic', 'fantasy'], category: 'nature' },
  { char: '🐢', name: 'turtle', keywords: ['slow'], category: 'nature' },
  { char: '🦖', name: 'trex', keywords: ['dinosaur', 'rex'], category: 'nature' },
  { char: '🐙', name: 'octopus', keywords: [], category: 'nature' },
  { char: '🐬', name: 'dolphin', keywords: ['ocean'], category: 'nature' },
  { char: '🌸', name: 'blossom', keywords: ['flower', 'spring'], category: 'nature' },
  { char: '🌻', name: 'sunflower', keywords: ['flower'], category: 'nature' },
  { char: '🌹', name: 'rose', keywords: ['flower', 'love'], category: 'nature' },
  { char: '🌵', name: 'cactus', keywords: ['desert'], category: 'nature' },
  { char: '🌲', name: 'tree', keywords: ['pine', 'forest'], category: 'nature' },
  { char: '🍀', name: 'clover', keywords: ['luck'], category: 'nature' },
  { char: '🌱', name: 'seedling', keywords: ['plant', 'grow', 'start'], category: 'nature' },
  { char: '🌍', name: 'earth', keywords: ['world', 'globe', 'planet'], category: 'nature' },
  { char: '🌙', name: 'moon', keywords: ['night'], category: 'nature' },
  { char: '⭐', name: 'star', keywords: ['favorite', 'important'], category: 'nature' },
  { char: '🌟', name: 'glowing star', keywords: ['sparkle', 'shine'], category: 'nature' },
  { char: '✨', name: 'sparkles', keywords: ['magic', 'shine', 'new'], category: 'nature' },
  { char: '⚡', name: 'lightning', keywords: ['power', 'fast', 'zap'], category: 'nature' },
  { char: '🔥', name: 'fire', keywords: ['hot', 'lit', 'urgent'], category: 'nature' },
  { char: '🌈', name: 'rainbow', keywords: ['pride'], category: 'nature' },
  { char: '❄️', name: 'snowflake', keywords: ['cold', 'freeze'], category: 'nature' },
  { char: '☀️', name: 'sun', keywords: ['sunny', 'bright'], category: 'nature' },
  { char: '☁️', name: 'cloud', keywords: ['weather'], category: 'nature' },
  { char: '💧', name: 'droplet', keywords: ['water', 'drop'], category: 'nature' },
  { char: '🌊', name: 'wave', keywords: ['ocean', 'water'], category: 'nature' },

  // Food & Drink
  { char: '🍎', name: 'apple', keywords: ['fruit', 'red'], category: 'food' },
  { char: '🍌', name: 'banana', keywords: ['fruit'], category: 'food' },
  { char: '🍊', name: 'orange', keywords: ['fruit'], category: 'food' },
  { char: '🍓', name: 'strawberry', keywords: ['fruit', 'berry'], category: 'food' },
  { char: '🍇', name: 'grapes', keywords: ['fruit'], category: 'food' },
  { char: '🍉', name: 'watermelon', keywords: ['fruit', 'summer'], category: 'food' },
  { char: '🥑', name: 'avocado', keywords: [], category: 'food' },
  { char: '🌶️', name: 'chili', keywords: ['spicy', 'hot', 'pepper'], category: 'food' },
  { char: '🍕', name: 'pizza', keywords: [], category: 'food' },
  { char: '🍔', name: 'burger', keywords: ['hamburger'], category: 'food' },
  { char: '🌮', name: 'taco', keywords: [], category: 'food' },
  { char: '🍩', name: 'donut', keywords: ['doughnut'], category: 'food' },
  { char: '🍪', name: 'cookie', keywords: [], category: 'food' },
  { char: '🎂', name: 'cake', keywords: ['birthday', 'celebrate'], category: 'food' },
  { char: '🍰', name: 'shortcake', keywords: ['cake', 'dessert'], category: 'food' },
  { char: '☕', name: 'coffee', keywords: ['drink', 'espresso'], category: 'food' },
  { char: '🍵', name: 'tea', keywords: ['drink'], category: 'food' },
  { char: '🍺', name: 'beer', keywords: ['drink'], category: 'food' },
  { char: '🍷', name: 'wine', keywords: ['drink'], category: 'food' },
  { char: '🥂', name: 'toast', keywords: ['cheers', 'celebrate'], category: 'food' },
  { char: '🍾', name: 'champagne', keywords: ['celebrate'], category: 'food' },

  // Activities
  { char: '🎯', name: 'target', keywords: ['goal', 'aim', 'bullseye'], category: 'activities' },
  { char: '🏆', name: 'trophy', keywords: ['win', 'award', 'champion'], category: 'activities' },
  { char: '🥇', name: 'gold medal', keywords: ['first', 'winner'], category: 'activities' },
  { char: '🎨', name: 'palette', keywords: ['art', 'design', 'paint'], category: 'activities' },
  { char: '🎭', name: 'theater', keywords: ['masks', 'drama'], category: 'activities' },
  { char: '🎬', name: 'clapper', keywords: ['film', 'movie', 'action'], category: 'activities' },
  { char: '🎤', name: 'mic', keywords: ['sing', 'speak'], category: 'activities' },
  { char: '🎧', name: 'headphones', keywords: ['music', 'audio'], category: 'activities' },
  { char: '🎵', name: 'music note', keywords: ['song', 'audio'], category: 'activities' },
  { char: '🎲', name: 'dice', keywords: ['game', 'random'], category: 'activities' },
  { char: '🎮', name: 'game', keywords: ['controller', 'play'], category: 'activities' },
  { char: '🧩', name: 'puzzle', keywords: ['piece', 'jigsaw'], category: 'activities' },
  { char: '🏈', name: 'football', keywords: ['sport'], category: 'activities' },
  { char: '⚽', name: 'soccer', keywords: ['football', 'sport'], category: 'activities' },
  { char: '🏀', name: 'basketball', keywords: ['sport'], category: 'activities' },

  // Travel
  {
    char: '🚀',
    name: 'rocket',
    keywords: ['launch', 'ship', 'deploy', 'fast'],
    category: 'travel',
  },
  { char: '✈️', name: 'plane', keywords: ['fly', 'travel'], category: 'travel' },
  { char: '🚗', name: 'car', keywords: ['drive'], category: 'travel' },
  { char: '🚚', name: 'truck', keywords: ['delivery', 'ship'], category: 'travel' },
  { char: '🚲', name: 'bike', keywords: ['bicycle', 'cycle'], category: 'travel' },
  { char: '⛵', name: 'boat', keywords: ['sail', 'ship'], category: 'travel' },
  { char: '🛸', name: 'ufo', keywords: ['saucer', 'alien'], category: 'travel' },
  { char: '🏠', name: 'house', keywords: ['home'], category: 'travel' },
  { char: '🏢', name: 'office', keywords: ['building', 'work'], category: 'travel' },
  { char: '🏗️', name: 'construction', keywords: ['building', 'wip'], category: 'travel' },
  { char: '🗺️', name: 'map', keywords: ['world', 'travel'], category: 'travel' },
  { char: '🗿', name: 'moai', keywords: ['stone', 'statue'], category: 'travel' },

  // Objects (most useful for labels)
  { char: '💻', name: 'laptop', keywords: ['computer', 'dev', 'code'], category: 'objects' },
  { char: '⌨️', name: 'keyboard', keywords: ['type', 'code'], category: 'objects' },
  { char: '🖥️', name: 'desktop', keywords: ['computer', 'monitor'], category: 'objects' },
  { char: '🖱️', name: 'mouse', keywords: ['computer', 'click'], category: 'objects' },
  { char: '📱', name: 'phone', keywords: ['mobile', 'cell'], category: 'objects' },
  { char: '📞', name: 'telephone', keywords: ['call'], category: 'objects' },
  { char: '📷', name: 'camera', keywords: ['photo'], category: 'objects' },
  { char: '📹', name: 'video', keywords: ['record', 'camera'], category: 'objects' },
  { char: '📺', name: 'tv', keywords: ['television'], category: 'objects' },
  { char: '💾', name: 'floppy', keywords: ['save', 'disk'], category: 'objects' },
  { char: '💿', name: 'cd', keywords: ['disc'], category: 'objects' },
  { char: '🔋', name: 'battery', keywords: ['power', 'energy'], category: 'objects' },
  { char: '🔌', name: 'plug', keywords: ['electric', 'power'], category: 'objects' },
  { char: '💡', name: 'idea', keywords: ['bulb', 'light', 'feature'], category: 'objects' },
  { char: '🔦', name: 'flashlight', keywords: ['torch', 'light'], category: 'objects' },
  { char: '🕯️', name: 'candle', keywords: ['light'], category: 'objects' },
  { char: '📡', name: 'antenna', keywords: ['satellite', 'signal'], category: 'objects' },
  { char: '💰', name: 'money bag', keywords: ['cash'], category: 'objects' },
  { char: '💳', name: 'card', keywords: ['payment', 'credit'], category: 'objects' },
  { char: '💎', name: 'gem', keywords: ['diamond', 'premium'], category: 'objects' },
  { char: '⚖️', name: 'balance', keywords: ['law', 'scale', 'justice'], category: 'objects' },
  { char: '🔧', name: 'wrench', keywords: ['tool', 'fix', 'repair'], category: 'objects' },
  { char: '🔨', name: 'hammer', keywords: ['tool', 'build'], category: 'objects' },
  { char: '🛠️', name: 'tools', keywords: ['hammer', 'wrench', 'config'], category: 'objects' },
  { char: '⚙️', name: 'gear', keywords: ['settings', 'config', 'cog'], category: 'objects' },
  { char: '🧰', name: 'toolbox', keywords: ['tools'], category: 'objects' },
  { char: '🔩', name: 'nut bolt', keywords: ['screw', 'hardware'], category: 'objects' },
  { char: '🧲', name: 'magnet', keywords: ['attract'], category: 'objects' },
  {
    char: '🧪',
    name: 'test tube',
    keywords: ['science', 'lab', 'experiment'],
    category: 'objects',
  },
  { char: '🧬', name: 'dna', keywords: ['biology'], category: 'objects' },
  { char: '🔬', name: 'microscope', keywords: ['science', 'research'], category: 'objects' },
  { char: '🔭', name: 'telescope', keywords: ['space', 'astronomy'], category: 'objects' },
  { char: '💊', name: 'pill', keywords: ['medicine'], category: 'objects' },
  { char: '💉', name: 'syringe', keywords: ['injection', 'shot'], category: 'objects' },
  { char: '🩹', name: 'bandage', keywords: ['bandaid', 'fix', 'patch'], category: 'objects' },
  { char: '🔑', name: 'key', keywords: ['unlock', 'password'], category: 'objects' },
  { char: '🔒', name: 'lock', keywords: ['secure', 'security', 'private'], category: 'objects' },
  { char: '🔓', name: 'unlock', keywords: ['open'], category: 'objects' },
  { char: '📅', name: 'calendar', keywords: ['date', 'schedule'], category: 'objects' },
  { char: '📆', name: 'tearoff calendar', keywords: ['date'], category: 'objects' },
  { char: '⏰', name: 'alarm', keywords: ['clock', 'time', 'wake'], category: 'objects' },
  { char: '⏱️', name: 'stopwatch', keywords: ['timer'], category: 'objects' },
  { char: '⌛', name: 'hourglass', keywords: ['time', 'wait'], category: 'objects' },
  { char: '📌', name: 'pin', keywords: ['pushpin', 'attach'], category: 'objects' },
  { char: '📍', name: 'location', keywords: ['pin', 'place'], category: 'objects' },
  { char: '📎', name: 'clip', keywords: ['attach', 'paperclip'], category: 'objects' },
  { char: '📏', name: 'ruler', keywords: ['measure'], category: 'objects' },
  { char: '✂️', name: 'scissors', keywords: ['cut'], category: 'objects' },
  { char: '📝', name: 'memo', keywords: ['note', 'write', 'edit'], category: 'objects' },
  { char: '✏️', name: 'pencil', keywords: ['write', 'edit'], category: 'objects' },
  { char: '🖊️', name: 'pen', keywords: ['write'], category: 'objects' },
  { char: '🖌️', name: 'brush', keywords: ['paint'], category: 'objects' },
  { char: '📚', name: 'books', keywords: ['library', 'read', 'docs'], category: 'objects' },
  { char: '📖', name: 'open book', keywords: ['read', 'docs'], category: 'objects' },
  { char: '📓', name: 'notebook', keywords: ['notes'], category: 'objects' },
  { char: '📋', name: 'clipboard', keywords: ['list', 'tasks'], category: 'objects' },
  { char: '📁', name: 'folder', keywords: ['files'], category: 'objects' },
  { char: '📂', name: 'open folder', keywords: ['files'], category: 'objects' },
  { char: '🗂️', name: 'dividers', keywords: ['files', 'organize'], category: 'objects' },
  { char: '📊', name: 'bar chart', keywords: ['analytics', 'data'], category: 'objects' },
  { char: '📈', name: 'chart up', keywords: ['growth', 'increase'], category: 'objects' },
  { char: '📉', name: 'chart down', keywords: ['decrease', 'loss'], category: 'objects' },
  { char: '📦', name: 'package', keywords: ['box', 'ship', 'release'], category: 'objects' },
  { char: '🎁', name: 'gift', keywords: ['present'], category: 'objects' },
  { char: '🏷️', name: 'label', keywords: ['tag'], category: 'objects' },
  { char: '🔖', name: 'bookmark', keywords: ['save'], category: 'objects' },
  { char: '📧', name: 'email', keywords: ['mail'], category: 'objects' },
  { char: '📮', name: 'postbox', keywords: ['mail', 'send'], category: 'objects' },
  { char: '🔍', name: 'search', keywords: ['find', 'magnify'], category: 'objects' },
  { char: '🔎', name: 'search right', keywords: ['find', 'magnify'], category: 'objects' },
  { char: '🎓', name: 'graduation', keywords: ['learn', 'school'], category: 'objects' },
  { char: '🎒', name: 'backpack', keywords: ['bag', 'school'], category: 'objects' },
  { char: '💼', name: 'briefcase', keywords: ['work', 'job'], category: 'objects' },
  { char: '🛡️', name: 'shield', keywords: ['defend', 'security'], category: 'objects' },
  { char: '⚔️', name: 'swords', keywords: ['battle', 'fight'], category: 'objects' },
  { char: '🧯', name: 'extinguisher', keywords: ['fire', 'safety'], category: 'objects' },

  // Symbols (crucial for status labels)
  { char: '❤️', name: 'red heart', keywords: ['love'], category: 'symbols' },
  { char: '💙', name: 'blue heart', keywords: ['love'], category: 'symbols' },
  { char: '💚', name: 'green heart', keywords: ['love'], category: 'symbols' },
  { char: '💛', name: 'yellow heart', keywords: ['love'], category: 'symbols' },
  { char: '🧡', name: 'orange heart', keywords: ['love'], category: 'symbols' },
  { char: '💜', name: 'purple heart', keywords: ['love'], category: 'symbols' },
  { char: '🖤', name: 'black heart', keywords: ['love'], category: 'symbols' },
  { char: '🤍', name: 'white heart', keywords: ['love'], category: 'symbols' },
  { char: '💔', name: 'broken heart', keywords: ['sad'], category: 'symbols' },
  { char: '💯', name: 'hundred', keywords: ['100', 'perfect', 'done'], category: 'symbols' },
  { char: '✅', name: 'check', keywords: ['done', 'yes', 'complete'], category: 'symbols' },
  { char: '☑️', name: 'ballot check', keywords: ['done', 'checkbox'], category: 'symbols' },
  { char: '✔️', name: 'checkmark', keywords: ['done', 'yes'], category: 'symbols' },
  { char: '❌', name: 'cross', keywords: ['x', 'cancel', 'no', 'wrong'], category: 'symbols' },
  { char: '❎', name: 'cross button', keywords: ['x', 'no'], category: 'symbols' },
  { char: '⭕', name: 'circle', keywords: ['o', 'ring'], category: 'symbols' },
  { char: '🛑', name: 'stop', keywords: ['halt', 'blocked'], category: 'symbols' },
  { char: '⛔', name: 'no entry', keywords: ['stop', 'blocked'], category: 'symbols' },
  { char: '🚫', name: 'prohibited', keywords: ['no', 'blocked', 'forbidden'], category: 'symbols' },
  { char: '⚠️', name: 'warning', keywords: ['caution', 'alert'], category: 'symbols' },
  { char: '🚨', name: 'siren', keywords: ['alert', 'urgent', 'emergency'], category: 'symbols' },
  { char: '❗', name: 'exclamation', keywords: ['important', 'alert'], category: 'symbols' },
  { char: '❓', name: 'question', keywords: ['huh', 'unknown'], category: 'symbols' },
  { char: '‼️', name: 'double exclamation', keywords: ['important'], category: 'symbols' },
  { char: '⁉️', name: 'exclamation question', keywords: ['what'], category: 'symbols' },
  { char: '♻️', name: 'recycle', keywords: ['refresh', 'reuse'], category: 'symbols' },
  { char: '🔄', name: 'reload', keywords: ['refresh', 'sync', 'retry'], category: 'symbols' },
  { char: '🔃', name: 'clockwise arrows', keywords: ['refresh', 'sync'], category: 'symbols' },
  { char: '➡️', name: 'right arrow', keywords: ['next'], category: 'symbols' },
  { char: '⬅️', name: 'left arrow', keywords: ['back', 'previous'], category: 'symbols' },
  { char: '⬆️', name: 'up arrow', keywords: ['top'], category: 'symbols' },
  { char: '⬇️', name: 'down arrow', keywords: ['bottom'], category: 'symbols' },
  { char: '↗️', name: 'up right', keywords: ['diagonal'], category: 'symbols' },
  { char: '↘️', name: 'down right', keywords: ['diagonal'], category: 'symbols' },
  { char: '▶️', name: 'play', keywords: ['start', 'go'], category: 'symbols' },
  { char: '⏸️', name: 'pause', keywords: ['wait', 'hold'], category: 'symbols' },
  { char: '⏹️', name: 'stop button', keywords: ['end'], category: 'symbols' },
  { char: '➕', name: 'plus', keywords: ['add', 'new'], category: 'symbols' },
  { char: '➖', name: 'minus', keywords: ['remove', 'subtract'], category: 'symbols' },
  { char: '✖️', name: 'multiply', keywords: ['times', 'cross'], category: 'symbols' },
  { char: '➗', name: 'divide', keywords: [], category: 'symbols' },
  { char: '♾️', name: 'infinity', keywords: ['forever'], category: 'symbols' },
  { char: '💬', name: 'speech', keywords: ['chat', 'comment', 'talk'], category: 'symbols' },
  { char: '💭', name: 'thought', keywords: ['think', 'bubble'], category: 'symbols' },
  { char: '🗯️', name: 'anger bubble', keywords: ['angry'], category: 'symbols' },
  { char: '🔴', name: 'red circle', keywords: ['red', 'stop', 'urgent'], category: 'symbols' },
  { char: '🟠', name: 'orange circle', keywords: ['orange'], category: 'symbols' },
  { char: '🟡', name: 'yellow circle', keywords: ['yellow'], category: 'symbols' },
  { char: '🟢', name: 'green circle', keywords: ['green', 'go', 'done'], category: 'symbols' },
  { char: '🔵', name: 'blue circle', keywords: ['blue'], category: 'symbols' },
  { char: '🟣', name: 'purple circle', keywords: ['purple'], category: 'symbols' },
  { char: '⚫', name: 'black circle', keywords: ['black'], category: 'symbols' },
  { char: '⚪', name: 'white circle', keywords: ['white'], category: 'symbols' },
  { char: '🟥', name: 'red square', keywords: ['red'], category: 'symbols' },
  { char: '🟩', name: 'green square', keywords: ['green'], category: 'symbols' },
  { char: '🟦', name: 'blue square', keywords: ['blue'], category: 'symbols' },
  { char: '🟨', name: 'yellow square', keywords: ['yellow'], category: 'symbols' },
];
