// Stamps a fresh build hash before each build/serve, replacing the source
// app's `vite-plugin-version.ts` (which injected a `define`d constant and
// wrote `public/version.json` at Vite's `buildStart`). Angular's esbuild-based
// builder has no equivalent plugin hook wired up, so this runs as an npm
// `pre*` lifecycle script instead and writes a small TS module that the app
// imports like any other source file.
import { writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';

const buildHash = Date.now().toString(36);

const versionJsonPath = fileURLToPath(
  new URL('../public/version.json', import.meta.url),
);
writeFileSync(versionJsonPath, JSON.stringify({ buildHash }));

const buildHashTsPath = fileURLToPath(
  new URL('../src/app/core/version/build-hash.ts', import.meta.url),
);
writeFileSync(
  buildHashTsPath,
  `// Auto-generated by scripts/stamp-version.mjs — do not edit by hand.\nexport const BUILD_HASH = '${buildHash}';\n`,
);
