name: Pull Request Checks

on:
  pull_request:

jobs:
  test:
    uses: ./.github/workflows/reusable-tests.yml
    secrets: inherit

  format:
    uses: ./.github/workflows/reusable-check.yml
    with:
      name: Prettier
      command: format:check

  cspell:
    uses: ./.github/workflows/reusable-check.yml
    with:
      name: Spell Check
      command: cspell
